Document: iaxflood
Title: Debian iaxflood Manual
Author: <insert document author here>
Abstract: This manual describes what iaxflood is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iaxflood/iaxflood.sgml.gz

Format: postscript
Files: /usr/share/doc/iaxflood/iaxflood.ps.gz

Format: text
Files: /usr/share/doc/iaxflood/iaxflood.text.gz

Format: HTML
Index: /usr/share/doc/iaxflood/html/index.html
Files: /usr/share/doc/iaxflood/html/*.html
